INSERT INTO PERSONAS(ID, NOMBRE, APELLIDOS, TIPO_IDENTIFICACION, IDENTIFICACION, TELEFONO, DIRECCION, ID_USUARIO)
              VALUES(1, 'Pedro', 'Martinez', 'DNI', '1234567', '654321', 'Madrid', 9);
INSERT INTO PERSONAS(ID, NOMBRE, APELLIDOS, TIPO_IDENTIFICACION, IDENTIFICACION, TELEFONO, DIRECCION, ID_USUARIO)
              VALUES(2, 'Aurora', 'Rivera', 'DNI', '2354789', '632587', 'Madrid', 10);
INSERT INTO PERSONAS(ID, NOMBRE, APELLIDOS, TIPO_IDENTIFICACION, IDENTIFICACION, TELEFONO, DIRECCION, ID_USUARIO)
              VALUES(5, 'Andres', 'Guadia', 'DNI', '8521456', '654789', 'Madrid', 11);

INSERT INTO USUARIOS(ID, USUARIO, CONTRASENA, PERFIL, LLAVE, FECHA_EXP_LLAVE)
              VALUES(9, 'PMARTINEZ', '14789', 'CLIENTE', '', null);
INSERT INTO USUARIOS(ID, USUARIO, CONTRASENA, PERFIL, LLAVE, FECHA_EXP_LLAVE)
              VALUES(10, 'ARIVERA', '12345', 'CLIENTE', '', null);
INSERT INTO USUARIOS(ID, USUARIO, CONTRASENA, PERFIL, LLAVE, FECHA_EXP_LLAVE)
              VALUES(11, 'AGUADIA', '11111', 'CLIENTE', '', null);

INSERT INTO VEHICULOS(ID, PLAZAS, DISPONIBLE, VALOR_DIA, CAMBIOS, CARROCERIA, COLOR, MARCA, TIPO_COMBUSTIBLE)
               VALUES(1, 5, true, 400.00, 'AUTOMATICO', 'TURISMO', 'ROJO', 'MAZDA', 'DIESEL');


