INSERT INTO PERSONAS(ID, NOMBRE, APELLIDOS, TIPO_IDENTIFICACION, IDENTIFICACION, TELEFONO, DIRECCION)
              VALUES(1, 'Pedro', 'Sanchez HDP', 'DNI', '1234567', '654321', 'Moncloa');

INSERT INTO VEHICULOS(ID, PLAZAS, DISPONIBLE, VALOR_DIA, CAMBIOS, CARROCERIA, COLOR, MARCA, TIPO_COMBUSTIBLE)
               VALUES(1, 5, true, 400.00, 'AUTOMATICO', 'TURISMO', 'ROJO', 'MAZDA', 'DIESEL');
