INSERT INTO USUARIOS(ID, USUARIO, CONTRASENA, PERFIL, LLAVE, FECHA_EXP_LLAVE)
              VALUES(9, 'PMARTINEZ', '14789', 'CLIENTE', '', null);
INSERT INTO USUARIOS(ID, USUARIO, CONTRASENA, PERFIL, LLAVE, FECHA_EXP_LLAVE)
              VALUES(10, 'ARIVERA', '12345', 'CLIENTE', '', null);
INSERT INTO USUARIOS(ID, USUARIO, CONTRASENA, PERFIL, LLAVE, FECHA_EXP_LLAVE)
              VALUES(11, 'AGUADIA', '11111', 'CLIENTE', '', null);
INSERT INTO USUARIOS(ID, USUARIO, CONTRASENA, PERFIL, LLAVE, FECHA_EXP_LLAVE)
              VALUES(12, 'JACOSTA', '96321', 'ADMIN', '', null);

INSERT INTO PERSONAS(ID, NOMBRE, APELLIDOS, TIPO_IDENTIFICACION, IDENTIFICACION, TELEFONO, DIRECCION, ID_USUARIO)
              VALUES(1, 'Pedro', 'Martinez', 'DNI', '1234567', '654321', 'Madrid', 9);
INSERT INTO PERSONAS(ID, NOMBRE, APELLIDOS, TIPO_IDENTIFICACION, IDENTIFICACION, TELEFONO, DIRECCION, ID_USUARIO)
              VALUES(2, 'Aurora', 'Rivera', 'DNI', '2354789', '632587', 'Madrid', 10);
INSERT INTO PERSONAS(ID, NOMBRE, APELLIDOS, TIPO_IDENTIFICACION, IDENTIFICACION, TELEFONO, DIRECCION, ID_USUARIO)
              VALUES(5, 'Andres', 'Guadia', 'DNI', '8521456', '654789', 'Madrid', 11);
INSERT INTO PERSONAS(ID, NOMBRE, APELLIDOS, TIPO_IDENTIFICACION, IDENTIFICACION, TELEFONO, DIRECCION, ID_USUARIO)
              VALUES(6, 'Jose', 'Acosta', 'DNI', '52874', '654780', 'Valencia', 12);

INSERT INTO VEHICULOS(ID, PLAZAS, DISPONIBLE, VALOR_DIA, CAMBIOS, CARROCERIA, COLOR, MARCA, TIPO_COMBUSTIBLE, IMAGEN)
               VALUES(20, 5, true, 200.00, 'AUTOMATICO', 'TURISMO', 'ROJO', 'MAZDA', 'DIESEL'
               ,'https://st2.depositphotos.com/1063296/8337/i/450/depositphotos_83378584-stock-photo-modern-compact-red-car-front.jpg');
INSERT INTO VEHICULOS(ID, PLAZAS, DISPONIBLE, VALOR_DIA, CAMBIOS, CARROCERIA, COLOR, MARCA, TIPO_COMBUSTIBLE, IMAGEN)
               VALUES(21, 5, true, 550.00, 'AUTOMATICO', 'SUV 4X4', 'GRIS', 'MERCEDES-BENZ', 'DIESEL'
               ,'https://www.shutterstock.com/image-photo/silver-car-standing-parking-lot-600nw-2462850863.jpg');
INSERT INTO VEHICULOS(ID, PLAZAS, DISPONIBLE, VALOR_DIA, CAMBIOS, CARROCERIA, COLOR, MARCA, TIPO_COMBUSTIBLE, IMAGEN)
               VALUES(22, 5, true, 300.00, 'AUTOMATICO', 'DEPORTIVO', 'AZUL', 'TOYOTA', 'DIESEL'
               ,'https://i0.statig.com.br/bancodeimagens/ey/zz/0d/eyzz0dzpwzjpx7gwpjjfdrxly.jpg');
INSERT INTO VEHICULOS(ID, PLAZAS, DISPONIBLE, VALOR_DIA, CAMBIOS, CARROCERIA, COLOR, MARCA, TIPO_COMBUSTIBLE, IMAGEN)
               VALUES(23, 5, true, 400.00, 'MANUAL', 'SUV 4X4', 'BLANCO', 'RENAULT', 'GLP'
               ,'https://www.shutterstock.com/image-photo/passenger-car-isolated-on-white-260nw-2288114495.jpg');
INSERT INTO VEHICULOS(ID, PLAZAS, DISPONIBLE, VALOR_DIA, CAMBIOS, CARROCERIA, COLOR, MARCA, TIPO_COMBUSTIBLE, IMAGEN)
               VALUES(24, 5, true, 250.00, 'AUTOMATICO', 'SUV 4X4', 'AMARILLO', 'MAZDA', 'DIESEL'
               ,'https://img.freepik.com/psd-gratis/coche-aislado-amarillo_23-2151852890.jpg?semt=ais_hybrid');
INSERT INTO VEHICULOS(ID, PLAZAS, DISPONIBLE, VALOR_DIA, CAMBIOS, CARROCERIA, COLOR, MARCA, TIPO_COMBUSTIBLE, IMAGEN)
               VALUES(25, 5, true, 300.00, 'MANUAL', 'TURISMO', 'GRIS', 'TOYOTA', 'GLP'
               ,'https://www.elcarrocolombiano.com/wp-content/uploads/2023/10/20231012-5-CARROS-SEDAN-MAS-BARATOS-DE-COLOMBIA-02.jpg');
INSERT INTO VEHICULOS(ID, PLAZAS, DISPONIBLE, VALOR_DIA, CAMBIOS, CARROCERIA, COLOR, MARCA, TIPO_COMBUSTIBLE, IMAGEN)
                VALUES(26, 5, true, 400.00, 'MANUAL', 'TURISMO', 'ROSA', 'MAZDA', 'DIESEL'
                ,'https://img.remediosdigitales.com/7c509f/toyota_ath_hybrid-/1366_2000.jpg');


